name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-secret gpg

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.POST_ENCRYPT_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import --batch --yes

      - name: Decrypt Post Files
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          git secret reveal -p "$GPG_PASSPHRASE"

      - run: |
          pip install mkdocs mkdocs-get-deps \
          mkdocs-git-authors-plugin mkdocs-git-committers-plugin \
          mkdocs-git-revision-date-localized-plugin mkdocs-material \
          mkdocs-material-extensions mkdocs-rss-plugin

      - run: mkdocs gh-deploy --force
